###
http://localhost:3010/api/v1/users

###
http://localhost:3010/api/v1/users/1

###
POST http://localhost:3010/api/v1/users
Content-Type: application/json

{
    "first_name":"Jay",
    "last_name":"Dizzle",
    "email": "jDizzy@inTheHouse.co",
    "password":"password",
    "display_name":"jDizzy"

}

###
PUT http://localhost:3010/api/v1/users/1
Content-Type: application/json

{
    "first_name":"Arnaldo"
}

###
DELETE http://localhost:3010/api/v1/users/21

###
http://localhost:3010/api/v1/users/profile

###
http://localhost:3010/api/v1/users/profile/1

###
PUT http://localhost:3010/api/v1/users/profile/1
Content-Type: application/json

{
    "display_name":"TestDisplayName"
}

###
POST http://localhost:3010/api/v1/users/login
Content-Type: application/json

{
    "email": "jDizzy@inTheHouse.co",
    "password":"5f4dcc3b5aa765d61d8327deb882cf99"
}